project:
  type: website
  output-dir: docs

website:
  description: "A blog about learning statistics"
  site-url: https://ravnc.github.io/mystatsdiary/
  title: "MyStatsDiary"
  sidebar: 
    contents: auto
format:
  html:
    theme:
      cosmo
    css: styles.css
    toc: true



